### PR TITLE
fix: Correcting the adding of a user to a travel so that the other participant also sees the travel on his screen

### PR DESCRIPTION
**Pull request by yassine04e**

### CODE REVIEW

**Review by ArthurChalard — CHANGES_REQUESTED** [review]
The fix works great, but it seams to still occurs for removal of users. We should use this PR to fix this as well.
Maybe we could also use this PR to fix the fact that there is an email in the add user box that we need to erase before typing the address we want.
Furthermore, I propose that we discuss briefly at the next standup of the fact that we duplicate the list of participants. Event though it can be kept up-to-date using transaction, it lead to this kind of issue.

**Comment by ArthurChalard** [comment]
Btw, don't forget to link the issue with your PR.

**Comment by yassine04e** [comment]
I agree. However, I think it is better to first fix the issue, then have a dedicated PR for the implementation of the transaction, so that we have a working app for the duration of the implementation.

**Review by ArthurChalard — APPROVED** [review]
Great, you fixed the removal of user. Thanks for the bugfix !

**Comment by ArthurChalard** [comment]
Fix #196

**Pull request merged**
