### PR TITLE
fix: close issue by updating package name to com.github.se.travelpouch

### LINKED ISSUE #4: Refactor: Update Package Name to com.github.se.travelpouch
Refactor the package name from com.android.sample to com.github.se.travelpouch. This ensure to be consistent with the bootcamp project and the conventional nomenclature.

### PR DESCRIPTION
**Pull request by appellet**
This pull request addresses the issue of updating the package name from com.android.sample to com.github.se.travelpouch. This change ensure to be consistent with the bootcamp and the conventional package name.

Related Issue: Closes #4

### CODE REVIEW

**Comment by ArthurChalard** [comment]
Hey,
This is a great idea. Maybe you should change the package name at the top of the files and remove the old directories to avoid duplication.

**Comment by appellet** [comment]
> Hey, This is a great idea. Maybe you should change the package name at the top of the files and remove the old directories to avoid duplication.

Done, thank you !

**Comment by ArthurChalard** [comment]
Great, you avoided the duplication, but the packages at the top of the files are still the old ones

**Comment by appellet** [comment]
> Great, you avoided the duplication, but the packages at the top of the files are still the old ones

Done, I change the package for all relevant files. Thanks for reminding me !

**Review by Unsaved2 — APPROVED** [review]
I reviewed the folder renaming, and everything looks good to me. The new naming conventions are clear and consistent with our project structure. I didn’t find any issues or errors in the changes

**Pull request merged**
